jails/urls.py
from django.urls import path

from . import views

app_name = 'jails'
urlpatterns = [
    path('', views.index, name='index'),
    path('new', views.new, name='new'),
    path('<str:jail_name>/', views.detail, name='detail'),
    path('<str:jail_name>/connect', views.connect, name='connect'),
    path('fetch_releases', views.fetch_releases, name='fetch_releases'),
    path('fetch_jails', views.fetch_jails, name='fetch_jails'),
    path('release_download', views.release_download, name='release_download'),
    path('start', views.start, name='start'),
    path('stop', views.stop, name='stop'),
    path('delete', views.delete, name='delete'),
    path('create', views.create, name='create'),
]

jaisting/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from django.views.generic.base import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html')),
    path('django_admins/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    url(r'^firewall/', include('firewall.urls')),
    url(r'^jails/', include('jails.urls')),
    url(r'^networks/', include('networks.urls')),
]

jails/views.py
from django.shortcuts import render
from django.http import Http404
from django.http import HttpResponse
from django.http import JsonResponse
from collections import OrderedDict
from django.contrib.auth.decorators import login_required
import json
import libioc


@login_required
def index(request):
    return render(request, 'jails/index.html')


@login_required
def detail(request, jail_name):
    try:
        jail = libioc.Jail(jail_name)
    except (libioc.errors.JailNotFound):
        raise Http404('%s does not found' % jail_name)
    return render(request, 'jails/detail.html', {'jail': jail})


@login_required
def connect(request, jail_name):
    try:
        jail = libioc.Jail(jail_name)
    except (libioc.errors.JailNotFound):
        raise Http404('%s does not found' % jail_name)
    return render(request, 'jails/connect.html', {'jail': jail})


@login_required
def new(request):
    try:
        distribution = libioc.Distribution()
    except(libioc.errors.IocException):
        raise Http404('Jails does not found')
    return render(request, 'jails/new.html', {'distribution': distribution.releases})


def fetch_jails(request):
    try:
        jails = libioc.Jails()
        jails_json = []
        key_id = 1
        for jail in jails:
            jail_dict = OrderedDict([
                ('id', key_id),
                ('jid', jail.jid),
                ('name', jail.name),
                ('status', 'up' if jail.running else 'down'),
                ('release', str(jail.release))
            ])
            jails_json.append(jail_dict)
            key_id += 1
        response = json.dumps(jails_json)
    except (libioc.errors.IocException):
        return HttpResponse('API Error', status=500)
    return HttpResponse(response)


def fetch_releases(request):
    try:
        distribution = libioc.Distribution()
        releases_json = []
        for release in distribution.releases:
            release_dict = OrderedDict([
                ('name', release.name),
                ('fetched', libioc.Release(release.name).fetched)
            ])
            releases_json.append(release_dict)
        response = json.dumps(releases_json)
    except (libioc.errors.IocException):
        return HttpResponse('API Error', status=500)
    return HttpResponse(response)


def release_download(request):
    try:
        response = json.loads(request.body)
        if response['release'] is None:
            return HttpResponse('release was none. Please selection release version', status=500)
        release = libioc.Release(response['release'])
        if release.fetched is True:
            return HttpResponse('%s was already downloaded. Skipping download.' % response['release'], status=409)
        release.fetch()
    except FileNotFoundError:
        release.destroy()
        return HttpResponse('File Download Error', status=404)
    except (libioc.errors.IocException):
        release.destroy()
        return HttpResponse('API Error', status=500)
    return HttpResponse(response)


def start(request):
    try:
        response = json.loads(request.body)
        jail = libioc.Jail.Jail(response['jail_name'])
        jail.start()
    except (libioc.errors.JailAlreadyRunning):
        return HttpResponse('%s is already running' % response['jail_name'], status=409)
    except (libioc.errors.JailNotFound):
        raise Http404('%s does not found' % response['jail_name'])
    return HttpResponse('OK')


def stop(request):
    try:
        response = json.loads(request.body)
        jail = libioc.Jail.Jail(response['jail_name'])
        jail.stop()
    except (libioc.errors.JailNotRunning):
        return HttpResponse('%s is not running' % response['jail_name'], status=409)
    except (libioc.errors.JailNotFound):
        raise Http404('%s does not found' % response['jail_name'])
    return HttpResponse('OK')


def delete(request):
    try:
        response = json.loads(request.body)
        jail = libioc.Jail(response['jail_name'])
        jail.destroy()
    except (libioc.errors.JailNotFound):
        return JsonResponse({'reason': '%s does not found' % response['jail_name']}, status=404)
    return HttpResponse('OK')


def create(request):
    try:
        response = json.loads(request.body)
        release = libioc.Release(response['release'])
        jail = libioc.Jail(data=dict(name=response['jail_name']), new=True)
        jail.create(release)
    except(libioc.errors.JailAlreadyExists):
        return JsonResponse({'reason': '%s is already exists' % response['jail_name']}, status=409)
    return HttpResponse('OK')

templates/jails/connect.html
{% extends 'application.html' %}

{% block title %}Jail Info{% endblock %}

{% block content %}
  <div class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
    <h2>Jail Connect</h2>
    <div class="table-responsive" id="app">
        <input type="hidden" id="jail_name" value="{{ jail.name }}">
        <jail-connect></jail-connect>
    </div>
  </div>
{% endblock %}

templates/jails/detail.html
{% extends 'application.html' %}

{% block title %}Jail Info{% endblock %}

{% block content %}
  <div class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
    <h2>Jail Info</h2>
    <div class="table-responsive">
      <table class="table table-striped table-sm">
        <thead>
        <tr>
          <th>Config</th>
          <th>Value</th>
        </tr>
        </thead>
        <tbody>
        {% for k, v in jail.config.items %}
          <tr>
            <td>{{ k }}</td>
            <td>{{ v }}</td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
      {% if jail.running == True %}
        <div class="float-md-right"><a class="btn btn-success new" href="/jails/{{jail.name}}/connect">Connect</a></div>
      {% endif %}
    </div>
  </div>
{% endblock %}

templates/jails/index.html
{% extends 'application.html' %}

{% block title %}Jail List{% endblock %}

{% block content %}
  <div class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
    <h2>Jails</h2>

    <div class="float-md-right"><a class="btn btn-success new" href="{% url 'jails:new' %}">New</a></div>

    <div class="table-responsive" id="app">
      <jails-index></jails-index>
    </div>
  </div>
{% endblock %}

templates/jails/new.html
{% extends 'application.html' %}

{% block title %}Jail New{% endblock %}

{% block content %}

  <div class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
    <div id="app">
      <jail-new></jail-new>
    </div>
  </div>
{% endblock %}