firewall/urls.py
from django.urls import path

from . import views

app_name = 'firewall'
urlpatterns = [
    path('', views.index, name='index'),
    path('fetch_all_lists', views.fetch_all_lists, name='fetch_all_lists'),
    path('add', views.add, name='add'),
    path('delete', views.delete, name='delete'),
]

jails/urls.py
from django.urls import path

from . import views

app_name = 'jails'
urlpatterns = [
    path('', views.index, name='index'),
    path('new', views.new, name='new'),
    path('<str:jail_name>/', views.detail, name='detail'),
    path('<str:jail_name>/connect', views.connect, name='connect'),
    path('fetch_releases', views.fetch_releases, name='fetch_releases'),
    path('fetch_jails', views.fetch_jails, name='fetch_jails'),
    path('release_download', views.release_download, name='release_download'),
    path('start', views.start, name='start'),
    path('stop', views.stop, name='stop'),
    path('delete', views.delete, name='delete'),
    path('create', views.create, name='create'),
]

jaisting/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from django.views.generic.base import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html')),
    path('django_admins/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    url(r'^firewall/', include('firewall.urls')),
    url(r'^jails/', include('jails.urls')),
    url(r'^networks/', include('networks.urls')),
]

networks/urls.py
from django.urls import path

from . import views

app_name = 'networks'
urlpatterns = [
    path('new', views.new, name='new'),
    path('create', views.create, name='create'),
    path('get_jails', views.get_jails, name='get_jails'),
]

templates/application.html
{% load render_bundle from webpack_loader %}
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="utf-8">
  <title>{% block title %}Jaisting{% endblock %}</title>
  {% render_bundle 'main' %}
</head>
<body>
{% csrf_token %}
<main class="dashboard">
  <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0">
    <a href="{% url 'jails:index' %}" class="navbar-brand col-sm-3 col-md-2 mr-0">Jails</a>
    <ul class="navbar-nav px-3">
      <li class="nav-item text-nowrap">
        <a class="nav-link" href="{% url 'logout' %}">log out</a>
      </li>
    </ul>
  </nav>
  <div class="container-fluid">
    <div class="row">
      <nav class="col-md-2 d-none d-md-block bg-light sidebar">
        <div class="sidebar-sticky">
          <ul class="nav flex-column">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'jails:index' %}">
                Dashboard
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'networks:new' %}">
                Networks
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'firewall:index' %}">
                Firewall
              </a>
            </li>
          </ul>
        </div>
      </nav>
      {% block content %}{% endblock %}
    </div>
  </div>
</main>
</body>
</html>

templates/index.html
{% extends 'top.html' %}

{% block title %}Jaisting{% endblock %}

{% block content %}
  <main class="top">
    <div class="cover-container d-flex h-100 p-3 mx-auto flex-column">
      <header class="masthead mb-auto">
        <div class="inner">
          <h3 class="masthead-brand">Jaisting</h3>
        </div>
      </header>
      <div role="main" class="inner cover">
        <h1 class="cover-heading">Jaisting</h1>
        <p class="lead">
          This Project is "hosting system" of jail for FreeBSD function.
        </p>
        <p class="lead">
          If you want use, Please sign-in.
        </p>
        <p class="lead">
          <a href="{% url 'login' %}" class="btn btn-lg btn-secondary">サインイン</a>
        </p>
      </div>
      <footer class="mastfoot mt-auto">
        <div class="inner">
          <p>Copyright (c) <a href="https://twitter.com/himrock922">@himrock922</a>. All Rights Reserved.</p>
        </div>
      </footer>
    </div>
  </main>
{% endblock %}

templates/top.html
{% load render_bundle from webpack_loader %}
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Jail Hosting System{% endblock %}</title>
      {% render_bundle 'main' %}
  </head>
  <body>
    {% block content %}{% endblock %}
  </body>
</html>